baseURL = ""
languageCode = "en-us"
title = "Liam's Favorite Things"
theme = "retrofulhugo"
relativeURLs = "true"
canonifyURLs = "true"

[Params]
  subtitle = ""
  logo = "img/srm.png"
  favicon = "img/favicon.ico"